name: Call Random Activity Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  call-random-activity:
  uses: sailwalpranjal/task-manager/.github/workflows/activity-CipherLab.yml@<commit-sha>
  
    secrets: inherit
